title: "Trang web về niệm Phật và học Phật"
author: "Phật tử Diệu Thắng ghi chép"
description: "1 Phật tử kiền thành muốn học Phật và chia sẻ." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
keywords: "Niệm Phật, Pháp sư Ấn Quang, An Sĩ Toàn Thư, Kinh A Di Đà, Hoà thượng Tuyên Hoá, Hoà thượng Tịnh Không"
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "thytran142@hotmail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

markdown:
plugins:
  - jekyll-paginate
  - jekyll-toc
paginate: 10
paginate_path: "/page/:num/"
show_excerpts: true
excerpt_length: 50
hide_credits: true


# TOC Settings
toc:
  min_level: 1
  max_level: 5
  list_class: toc
  sublist_class: toc__sublist
